# Конфигурация AHK Rust

[logging]
level = "info"
format = "pretty"  # pretty, json
filter = "ahk_rust=info"

[input]
device_path = "auto"  # auto или путь к устройству

[repeat]
repeat_delay_ms = 50

[window]
detection_mode = "dbus"  # dbus, polling
polling_interval_ms = 1000
# Фильтры окон - если пустые, то работает для всех окон
window_title_patterns = []

# Примеры маппингов клавиш для повторения
[[mappings]]
key = "j"
modifiers = []

[[mappings]]
key = "k" 
modifiers = []

[[mappings]]
key = "h"
modifiers = []

[[mappings]]
key = "l"
modifiers = []

[[mappings]]
key = "space"
modifiers = ["ctrl"]